// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jipoxszqohewelnnjpaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppcG94c3pxb2hld2Vsbm5qcGFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxOTQ4NjMsImV4cCI6MjA1Nzc3MDg2M30._h2ZCNQyJVWAKO66JC7jlj43vjHgZNxrWI3XjvOEGDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);